version: '3.8'
services:
  # web: 
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports: 
  #     - "8000:8000"
  #   # volumes: 
  #   #   - .:.
  #   env_file:
  #     - .env
  #   # environment:
  #   #   - DB_NAME: ${DB_NAME}
  #   #   - DB_USER: ${DB_USER}
  #   #   - DB_PASSWORD: ${DB_PASSWORD}
  #   #   - DB_PORT: ${DB_PORT}
  #   #   - DB_URL: ${DB_URL}
  #   depends_on:
  #     - postgres
  #     - redis
  #   # restart: always
  #   networks: 
  #     - lan
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # networks: 
    #   - lan
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#     networks: 
#       - lan
# networks: 
#   lan:
